version: "1.0"
services:
  frontend:
    image: paperless:nginx
    build:
      dockerfile: ui/Dockerfile
    ports:
      - "8080:80"
  backend:
    image: paperless:openjdk
    build:
      dockerfile: Dockerfile
    ports:
      - "8088:8088"

  postgres_db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'paperless_db'
    ports:
      - "5432:5454"

    volumes:
      - ./postgres_db-data:/var/lib/postgresql/data