package org.openapitools.service.common.enums;



public enum FileContentTypeEnum {

    XLSX("xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    XLTX("xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template"),
    POTX("potx", "application/vnd.openxmlformats-officedocument.presentationml.template"),
    PPSX("ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow"),
    PPTX("pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    SLDX("sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide"),
    DOCX("docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    DOTX("dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template"),
    XLAM("xlam", "application/vnd.ms-excel.addin.macroEnabled.12"),
    XLSB("xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"),
    APK("apk", "application/vnd.android.package-archive"),
    HQX("hqx", "application/mac-binhex40"),
    CPT("cpt", "application/mac-compactpro"),
    DOC("doc", "application/msword"),
    OGG("ogg", "application/ogg"),
    PDF("pdf", "application/pdf"),
    RTF("rtf", "text/rtf"),
    MIF("mif", "application/vnd.mif"),
    XLS("xls", "application/vnd.ms-excel"),
    PPT("ppt", "application/vnd.ms-powerpoint"),
    ODC("odc", "application/vnd.oasis.opendocument.chart"),
    ODB("odb", "application/vnd.oasis.opendocument.database"),
    ODF("odf", "application/vnd.oasis.opendocument.formula"),
    ODG("odg", "application/vnd.oasis.opendocument.graphics"),
    OTG("otg", "application/vnd.oasis.opendocument.graphics-template"),
    ODI("odi", "application/vnd.oasis.opendocument.image"),
    ODP("odp", "application/vnd.oasis.opendocument.presentation"),
    OTP("otp", "application/vnd.oasis.opendocument.presentation-template"),
    ODS("ods", "application/vnd.oasis.opendocument.spreadsheet"),
    OTS("ots", "application/vnd.oasis.opendocument.spreadsheet-template"),
    ODT("odt", "application/vnd.oasis.opendocument.text"),
    ODM("odm", "application/vnd.oasis.opendocument.text-master"),
    OTT("ott", "application/vnd.oasis.opendocument.text-template"),
    OTH("oth", "application/vnd.oasis.opendocument.text-web"),
    SXW("sxw", "application/vnd.sun.xml.writer"),
    STW("stw", "application/vnd.sun.xml.writer.template"),
    SXC("sxc", "application/vnd.sun.xml.calc"),
    STC("stc", "application/vnd.sun.xml.calc.template"),
    SXD("sxd", "application/vnd.sun.xml.draw"),
    STD("std", "application/vnd.sun.xml.draw.template"),
    SXI("sxi", "application/vnd.sun.xml.impress"),
    STI("sti", "application/vnd.sun.xml.impress.template"),
    SXG("sxg", "application/vnd.sun.xml.writer.global"),
    SXM("sxm", "application/vnd.sun.xml.math"),
    SIS("sis", "application/vnd.symbian.install"),
    WBXML("wbxml", "application/vnd.wap.wbxml"),
    WMLC("wmlc", "application/vnd.wap.wmlc"),
    WMLSC("wmlsc", "application/vnd.wap.wmlscriptc"),
    BCPIO("bcpio", "application/x-bcpio"),
    TORRENT("torrent", "application/x-bittorrent"),
    BZ2("bz2", "application/x-bzip2"),
    VCD("vcd", "application/x-cdlink"),
    PGN("pgn", "application/x-chess-pgn"),
    CPIO("cpio", "application/x-cpio"),
    CSH("csh", "application/x-csh"),
    DVI("dvi", "application/x-dvi"),
    SPL("spl", "application/x-futuresplash"),
    GTAR("gtar", "application/x-gtar"),
    HDF("hdf", "application/x-hdf"),
    JAR("jar", "application/x-java-archive"),
    JNLP("jnlp", "application/x-java-jnlp-file"),
    JS("js", "application/x-javascript"),
    KSP("ksp", "application/x-kspread"),
    CHRT("chrt", "application/x-kchart"),
    KIL("kil", "application/x-killustrator"),
    LATEX("latex", "application/x-latex"),
    RPM("rpm", "application/x-rpm"),
    SH("sh", "application/x-sh"),
    SHAR("shar", "application/x-shar"),
    SWF("swf", "application/x-shockwave-flash"),
    SIT("sit", "application/x-stuffit"),
    SV4CPIO("sv4cpio", "application/x-sv4cpio"),
    SV4CRC("sv4crc", "application/x-sv4crc"),
    TAR("tar", "application/x-tar"),
    TCL("tcl", "application/x-tcl"),
    TEX("tex", "application/x-tex"),
    MAN("man", "application/x-troff-man"),
    ME("me", "application/x-troff-me"),
    MS("ms", "application/x-troff-ms"),
    USTAR("ustar", "application/x-ustar"),
    SRC("src", "application/x-wais-source"),
    ZIP("zip", "application/zip"),
    M3U("m3u", "audio/x-mpegurl"),
    RA("ra", "audio/x-pn-realaudio"),
    WAV("wav", "audio/x-wav"),
    WMA("wma", "audio/x-ms-wma"),
    WAX("wax", "audio/x-ms-wax"),
    PDB("pdb", "chemical/x-pdb"),
    XYZ("xyz", "chemical/x-xyz"),
    BMP("bmp", "image/bmp"),
    GIF("gif", "image/gif"),
    IEF("ief", "image/ief"),
    PNG("png", "image/png"),
    WBMP("wbmp", "image/vnd.wap.wbmp"),
    RAS("ras", "image/x-cmu-raster"),
    PNM("pnm", "image/x-portable-anymap"),
    PBM("pbm", "image/x-portable-bitmap"),
    PGM("pgm", "image/x-portable-graymap"),
    PPM("ppm", "image/x-portable-pixmap"),
    RGB("rgb", "image/x-rgb"),
    XBM("xbm", "image/x-xbitmap"),
    XPM("xpm", "image/x-xpixmap"),
    XWD("xwd", "image/x-xwindowdump"),
    CSS("css", "text/css"),
    RTX("rtx", "text/richtext"),
    TSV("tsv", "text/tab-separated-values"),
    JAD("jad", "text/vnd.sun.j2me.app-descriptor"),
    WML("wml", "text/vnd.wap.wml"),
    WMLS("wmls", "text/vnd.wap.wmlscript"),
    ETX("etx", "text/x-setext"),
    MXU("mxu", "video/vnd.mpegurl"),
    FLV("flv", "video/x-flv"),
    WM("wm", "video/x-ms-wm"),
    WMV("wmv", "video/x-ms-wmv"),
    WMX("wmx", "video/x-ms-wmx"),
    WVX("wvx", "video/x-ms-wvx"),
    AVI("avi", "video/x-msvideo"),
    MOVIE("movie", "video/x-sgi-movie"),
    ICE("ice", "x-conference/x-cooltalk"),
    GP3("3gp", "video/3gpp"),
    AI("ai", "application/postscript"),
    AIF("aif", "audio/x-aiff"),
    AIFC("aifc", "audio/x-aiff"),
    AIFF("aiff", "audio/x-aiff"),
    ASC("asc", "text/plain"),
    ATOM("atom", "application/atom+xml"),
    AU("au", "audio/basic"),
    BIN("bin", "application/octet-stream"),
    CDF("cdf", "application/x-netcdf"),
    CGM("cgm", "image/cgm"),
    CLASS("class", "application/octet-stream"),
    DCR("dcr", "application/x-director"),
    DIF("dif", "video/x-dv"),
    DIR("dir", "application/x-director"),
    DJV("djv", "image/vnd.djvu"),
    DJVU("djvu", "image/vnd.djvu"),
    DLL("dll", "application/octet-stream"),
    DMG("dmg", "application/octet-stream"),
    DMS("dms", "application/octet-stream"),
    DTD("dtd", "application/xml-dtd"),
    DV("dv", "video/x-dv"),
    DXR("dxr", "application/x-director"),
    EPS("eps", "application/postscript"),
    EXE("exe", "application/octet-stream"),
    EZ("ez", "application/andrew-inset"),
    GRAM("gram", "application/srgs"),
    GRXML("grxml", "application/srgs+xml"),
    GZ("gz", "application/x-gzip"),
    TGZ("tgz", "application/x-gzip"),
    HTM("htm", "text/html"),
    HTML("html", "text/html"),
    ICO("ico", "image/x-icon"),
    ICS("ics", "text/calendar"),
    IFB("ifb", "text/calendar"),
    IGES("iges", "model/iges"),
    IGS("igs", "model/iges"),
    JP2("jp2", "image/jp2"),
    JPE("jpe", "image/jpeg"),
    JPEG("jpeg", "image/jpeg"),
    JPG("jpg", "image/jpeg"),
    KAR("kar", "audio/midi"),
    LHA("lha", "application/octet-stream"),
    LZH("lzh", "application/octet-stream"),
    M4A("m4a", "audio/mp4a-latm"),
    M4P("m4p", "audio/mp4a-latm"),
    M4U("m4u", "video/vnd.mpegurl"),
    M4V("m4v", "video/x-m4v"),
    MAC("mac", "image/x-macpaint"),
    MATHML("mathml", "application/mathml+xml"),
    MESH("mesh", "model/mesh"),
    MID("mid", "audio/midi"),
    MIDI("midi", "audio/midi"),
    MOV("mov", "video/quicktime"),
    MP2("mp2", "audio/mpeg"),
    MP3("mp3", "audio/mpeg"),
    MP4("mp4", "video/mp4"),
    MPE("mpe", "video/mpeg"),
    MPEG("mpeg", "video/mpeg"),
    MPG("mpg", "video/mpeg"),
    MPGA("mpga", "audio/mpeg"),
    MSH("msh", "model/mesh"),
    NC("nc", "application/x-netcdf"),
    ODA("oda", "application/oda"),
    OGV("ogv", "video/ogv"),
    PCT("pct", "image/pict"),
    PIC("pic", "image/pict"),
    PICT("pict", "image/pict"),
    PNT("pnt", "image/x-macpaint"),
    PNTG("pntg", "image/x-macpaint"),
    PS("ps", "application/postscript"),
    QT("qt", "video/quicktime"),
    QTI("qti", "image/x-quicktime"),
    QTIF("qtif", "image/x-quicktime"),
    RAM("ram", "audio/x-pn-realaudio"),
    RDF("rdf", "application/rdf+xml"),
    RM("rm", "application/vnd.rn-realmedia"),
    ROFF("roff", "application/x-troff"),
    SGM("sgm", "text/sgml"),
    SGML("sgml", "text/sgml"),
    SILO("silo", "model/mesh"),
    SKD("skd", "application/x-koan"),
    SKM("skm", "application/x-koan"),
    SKP("skp", "application/x-koan"),
    SKT("skt", "application/x-koan"),
    SMI("smi", "application/smil"),
    SMIL("smil", "application/smil"),
    SND("snd", "audio/basic"),
    SO("so", "application/octet-stream"),
    SVG("svg", "image/svg+xml"),
    T("t", "application/x-troff"),
    TEXI("texi", "application/x-texinfo"),
    TEXINFO("texinfo", "application/x-texinfo"),
    TIF("tif", "image/tiff"),
    TIFF("tiff", "image/tiff"),
    TR("tr", "application/x-troff"),
    TXT("txt", "text/plain"),
    VRML("vrml", "model/vrml"),
    VXML("vxml", "application/voicexml+xml"),
    WEBM("webm", "video/webm"),
    WRL("wrl", "model/vrml"),
    XHT("xht", "application/xhtml+xml"),
    XHTML("xhtml", "application/xhtml+xml"),
    XML("xml", "application/xml"),
    XSL("xsl", "application/xml"),
    XSLT("xslt", "application/xslt+xml"),
    XUL("xul", "application/vnd.mozilla.xul+xml"),
    WEBP("webp", "image/webp"),
    PSD("psd", "image/vnd.adobe.photoshop"),
    DOWN_LOAD("download", "application/x-msdownload");

    private final String fileSuffix;
    private final String contentType;

    public String getFileSuffix() {
        return fileSuffix;
    }

    public String getContentType() {
        return contentType;
    }

    public static FileContentTypeEnum getBySuffix(String suffix) {
        for (FileContentTypeEnum value : FileContentTypeEnum.values()) {
            if (value.getFileSuffix().equalsIgnoreCase(suffix)) {
                return value;
            }
        }
        return DOWN_LOAD;
    }


    FileContentTypeEnum(String fileSuffix, String contentType) {
        this.fileSuffix = fileSuffix;
        this.contentType = contentType;

    }
}
